export const jokes = [
  "Why did the computer go to therapy? It had too many unresolved issues.",
  "Why do Python programmers prefer dark mode? Because light mode doesn’t have any indentation.",
  "Why did the HTML tag break up with the CSS class? It found someone more inline.",
  "Why can’t programmers play hide and seek? Because good luck hiding when they can’t stop debugging.",
  "Why did the developer bring a ladder to work? To reach the high-level code.",
  "Why do C# developers make terrible musicians? Because they always forget to close their braces.",
  "What do you call a programmer from Finland? Nerdic.",
  "Why don’t programmers like to go fishing? They can’t handle the hook.",
  "I think I lost my C++ pointer... Now I’m completely lost!",
  "Why did the computer break up with the internet? It found a better connection.",
  "Why don’t Java developers ever mix their drinks? They can’t handle exceptions.",
  "Why did the computer catch a cold? It left its Windows open.",
  "Why did the programmer get kicked out of school? He kept trying to code his way out of problems.",
  "How do you know if a developer is at a party? Don’t worry, they’ll tell you.",
  "Why did the developer quit his job? He didn’t get arrays.",
  "What did the HTML say to the CSS? You complete me.",
  "Why did the web developer go broke? Because he used all his cache on his website.",
  "Why are Java developers bad at relationships? They don’t know how to handle exceptions.",
  "How do developers take their coffee? With a bit of Java.",
  "Why do developers always have a tough time with relationships? They can’t commit."
];
